from pydantic import BaseModel, Field

class MCPClientModelRequest(BaseModel):
    """
    Base model for MCP client requests.
    """
    user_query: str = Field(
        ...,
        description="The user's query to be processed by the MCP client.",
        example="Add two numbers 5 and 10 and return the result."
    )

class MCPClientModelResponse(BaseModel):
    """
    Base model for MCP client responses.
    """
    response: str = Field(
        ...,
        description="The response generated by the MCP client based on the user's query.",
        example="The result of adding 5 and 10 is 15."
    )
