version: '3.8'

services:
  ollama:
    build: ./ollama  # Path to the Ollama Dockerfile
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"  # Ollama API port
    volumes:
      - ollama_data:/root/.ollama  # Ollama persistent data volume
    networks:
      - ollama_network

  mcp-server:
    build: ./mcp-server  # Path to the MCP Server Dockerfile
    container_name: mcp_server
    restart: always
    ports:
      - "8080:8080"  # MCP Server port
    networks:
      - ollama_network  # Ensure both services are on the same network

  mcp-client:
    build: ./mcp-client  # Path to the MCP Client Dockerfile
    container_name: mcp_client
    restart: always
    environment:
      - OLLAMA_LLM_MODEL_NAME=llama3.2:latest  # Specify the LLM model name
      - MCP_SERVER_ENDPOINT=http://mcp_server:8080/mcp # MCP Server endpoint
      - OLLAMA_API_URL=http://ollama:11434  # Ollama API URL
    depends_on:
      - mcp-server  # Ensure MCP Server is started before mcp-client
      - ollama # Ensure Ollama is available for the client
    ports:
      - "8000:8000"  # MCP Client service port
    networks:
      - ollama_network  # Ensure both services are on the same network
  chat_app:
    build: ./chat-app  # Path to the React Native Dockerfile
    container_name: chat-app
    restart: always
    depends_on:
      - mcp-client  # Ensure mcp-client service starts before frontend
    ports:
      - "5000:5000"
    networks:
      - ollama_network  # Ensure all services communicate properly

networks:
  ollama_network:
    driver: bridge

volumes:
  ollama_data:  # Named volume for Ollama's data
